import { Exo_2 } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";

// Import Exo 2 from Google Fonts
const exo2 = Exo_2({
  weight: "500",
  style: "italic",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create LearnLabs App",
  description: "Generated by Purna",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <GoogleOneTap />
        <body
          className={`${exo2.className} antialiased`}
        >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
