export default[
    {
        id:1,
        name:'Programming',
        icon:'/category.png',
        prompt:''
    },
    {
        id:1,
        name:'Health',
        icon:'/lotus.png',
        prompt:''
    },
    {
        id:1,
        name:'Creative',
        icon:'/creative.png',
        prompt:''
    },
]